// POST LOGIN
export const POST_FORGOTPASS_REQUEST = "POST_FORGOTPASS_REQUEST";
export const POST_FORGOTPASS_SUCCESS = "POST_FORGOTPASS_SUCCESS";
export const POST_FORGOTPASS_FAILURE = "POST_FORGOTPASS_FAILURE";
